export namespace Enums {
    export enum EntityType {
        Environment = 0,
        Item = 1,
        NPC = 2,
        Player = 3,
    }

    export enum TargetAction {
        attack = 0,
        talk_to = 1,
        pick_up = 2,
        equip = 3,
        unequip = 4,
        use = 5,
        drop = 6,
        examine = 7,
        bank = 8,
        shop = 9,
        cook_on = 10,
        fish_in = 11,
        mine = 12,
        chop = 13,
        gather_from = 14,
        smith_at = 15,
        smelt_at = 16,
        teleport = 17,
        climb_up = 18,
        climb_down = 19,
        climb_same_map_level = 20,
        open = 21,
        unlock = 22,
        brew = 23,
        cast = 24,
        auto_cast = 25,
        stop_auto_casting = 26,
        mine_through = 27,
        go_through = 28,
        craft = 29,
        sleep_in = 30,
        touch = 31,
        craft_at = 32,
        use_item_with = 33,
        walk_here = 34,
        trade_with = 35,
        follow = 36,
        inspect = 37,
        cancel = 38,
        add_entity = 39,
        edit_entity = 40,
    }

    export enum MenuType {
        Bank = 0,
        Shop = 1,
        Inventory = 2,
        TradeInventory = 3,
        TradeMyOfferedItems = 4,
        TradeOtherPlayerOfferedItems = 5,
        Loadout = 6,
        ChangeAppearance = 7,
        Anvil = 8,
        Furnace = 9,
        CookingRange = 10,
        Magic = 11,
        PotionMaking = 12,
        Welcome = 13,
        SmeltingKiln = 14,
        CameraSettings = 15,
        SkillGuide = 16,
        Loot = 17,
        FriendList = 18,
        Stats = 19,
        Quests = 20,
        Settings = 21,
        TextInput = 22,
        Confirmation = 23,
        Chat = 24,
        PrivateChat = 25,
        TradeMenu = 26,
        TreasureMap = 27,
        GraphicsSettings = 28,
        ChatSettings = 29,
        CraftingTable = 30,
    }

    export enum ItemAction {
        use = 0,
        drop = 1,
        examine = 2,
        eat = 3,
        drink = 4,
        equip = 5,
        unequip = 6,
        withdraw = 7,
        withdrawiou = 8,
        deposit = 9,
        offer = 10,
        revoke = 11,
        buy = 12,
        sell = 13,
        open = 14,
        check_price = 15,
        create = 16,
        rub = 17,
        dropx = 18,
        look_at = 19,
        dig = 20,
        discard = 21,
    }

    export enum ReorganizeType {
        Swap = 0,
        Insert = 1,
    }

    export enum CombatStyle {
        Melee = 0,
        Ranged = 1,
        Magic = 2,
    }

    export enum DamageType {
        Melee = 0,
        Ranged = 1,
        Magic = 2,
        Poison = 3,
        Bleed = 4,
    }

    export enum CauseOfDeath {
        PVP = 0,
        PVE = 1,
        Environment = 2,
    }

    export enum Skill {
        hitpoints = 0,
        accuracy = 1,
        strength = 2,
        defense = 3,
        magic = 4,
        fishing = 5,
        cooking = 6,
        forestry = 7,
        mining = 8,
        crafting = 9,
        crime = 10,
        potionmaking = 11,
        smithing = 12,
        harvesting = 13,
        enchanting = 14,
        range = 15,
    }
}
