name: CI

on:
  workflow_call:
    outputs:
      build-artifact:
        description: "Name of the build artifact"
        value: ${{ jobs.build.outputs.artifact-name }}

env:
  NODE_VERSION: '22'
  PNPM_VERSION: 8

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}
      - name: Install Dependencies
        run: pnpm install
      - name: Lint
        run: pnpm -r lint

  type-check:
    name: Type Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}
      - name: Install Dependencies
        run: pnpm install
      - name: Type Check
        run: pnpm -r type-check

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [lint, type-check]
    outputs:
      artifact-name: ${{ steps.artifact.outputs.name }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}
      - name: Install Dependencies
        run: pnpm install
      - name: Build Types
        run: pnpm --filter @bgscrew/highspell-types build:ci
        env:
          CLIENT_URL: ${{ secrets.CLIENT_URL }}
      - name: Build All Packages
        run: pnpm -r build
      - name: Set artifact name
        id: artifact
        run: echo "name=highspell-types-build-${{ github.sha }}" >> $GITHUB_OUTPUT
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.artifact.outputs.name }}
          path: |
            packages/types/dist/
            packages/types/src/
            packages/types/package.json
            packages/build-core/src/
            packages/build-core/package.json
            packages/babel-build-plugin/src/
            packages/babel-build-plugin/package.json
            packages/swc-build-plugin/src/
            packages/swc-build-plugin/package.json
            packages/vite-build-plugin/src/
            packages/vite-build-plugin/package.json
          retention-days: 1

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}
      - name: Install Dependencies
        run: pnpm install
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.build.outputs.artifact-name }}
          path: packages
      - name: Run Tests
        run: pnpm test:all