name: Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '19 0 * * *'
  workflow_dispatch:
    inputs:
      version_type:
        description: 'Version bump type'
        required: false
        type: choice
        options:
          - auto
          - patch
          - minor
          - major
        default: 'auto'

jobs:
  ci:
    name: CI
    uses: ./.github/workflows/ci.yml

  codeql:
    name: CodeQL Analysis
    permissions:
      actions: read
      contents: read
      security-events: write
      packages: read
    uses: ./.github/workflows/codeql.yml

  cd:
    name: CD
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
    needs: [ci, codeql]
    permissions:
      contents: write
      packages: write
      id-token: write
    uses: ./.github/workflows/cd.yml
    with:
      build-artifact: ${{ needs.ci.outputs.build-artifact }}
      version-type: ${{ inputs.version_type || 'auto' }}
    secrets: inherit