name: Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight
  workflow_dispatch:
    inputs:
      version_type:
        description: 'Version bump type'
        required: false
        type: choice
        options:
          - auto
          - patch
          - minor
          - major
        default: 'auto'

jobs:
  ci:
    name: CI
    uses: ./.github/workflows/ci.yml

  cd:
    name: CD
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
    needs: ci
    uses: ./.github/workflows/cd.yml
    with:
      build-artifact: ${{ needs.ci.outputs.build-artifact }}
      version-type: ${{ inputs.version_type || 'auto' }}
    secrets: inherit